### ISSUE TITLE
Fix/improve concurrent session handling

### ISSUE THREAD

**Issue by shankari** [NREL/crowdsource-mask-wearing#13]
If a user starts a session, and then navigates away from the page, their data collection is blocked forever. This is because starting a new session will fail because there is an ongoing session.

Options for navigating away include:
- clicking one of the other links on the sidebar
- killing the browser/browser tab

We can try to prevent the first, but we cannot prevent the second. If we get an error while creating a session, we need to either terminate the existing session or create a new one.

**Comment by andyduvall** [comment]
Can there be a warning: "leaving this page will terminate the session and delete the data"

**Comment by shankari** [comment]
warning won't fix the case of user killing the browser. It won't even work for the case of the user closing the window. It will only work for the case of the user clicking on one of the sidebar links. So we need to solve this anyway.

**Comment by shankari** [comment]
This probably needs to be fixed too since it was a user report.

A fairly simple interim fix might be to retrieve the existing session and just use it instead of terminating it or creating a new one, since the common case would be for users to navigate away by mistake temporarily and then want to restart the session. I can take a stab at this at sometime this weekend.

**Comment by shankari** [comment]
While fixing this, also make the location required in the form

**Comment by fua0004673** [comment]
@shankari, is this issue still relevant considering #36 has been merged in?

**Comment by shankari** [comment]
Not for this milestone, certainly. When we switch towards more local operation, we will have to deal with this again because there could be session conflicts on the server that we need to resolve. Closing this for now.
