### ISSUE TITLE
Better error reporting on the UI

### ISSUE THREAD

**Issue by shankari** [NREL/crowdsource-mask-wearing#14]
The server actually returns a pretty nice error message indicating what the problem was. But that detail is lost on the client side. Instead, the call stack gets lost somewhere within the observable world.

For example on specifying an invalid username/password, we get the error

```
columnNumber: 68
fileName: "http://localhost:4200/default~feature-maskreport-maskreport-module~feature-user-user-module.js"
lineNumber: 2062
message: "rxjs__WEBPACK_IMPORTED_MODULE_2__.Observable.throw is not a function"
stack: "intercept/<@http://localhost:4200/default~feature-maskreport-maskreport-module~feature-user-user-module.js:2062:68
error@http://localhost:4200/vendor.js:101371:31
onLoad@http://localhost:4200/vendor.js:18810:30
invokeTask@http://localhost:4200/polyfills.js:412:35
onInvokeTask@http://localhost:4200/vendor.js:56702:33
invokeTask@http://localhost:4200/polyfills.js:411:40
runTask@http://localhost:4200/polyfills.js:180:51
invokeTask@http://localhost:4200/polyfills.js:493:38
invokeTask@http://localhost:4200/polyfills.js:1634:18
globalZoneAwareCallback@http://localhost:4200/polyfills.js:1671:25\n
```

And what is actually displayed to the user is `"rxjs__WEBPACK_IMPORTED_MODULE_2__.Observable.throw is not a function"`, which is completely unintelligible.

Would be good to display the actual error message from the host instead, which is

```
{"error":{"message":"Username or email does not exist","details":"UnauthorizedError: Username or email does not exist..."}}
```

**Comment by shankari** [comment]
I wonder if this is a result of using observable instead of Promises. I am a lot more familiar with Promises myself, but it looks like the angular world likes observables?

**Comment by andyduvall** [comment]
I have to leave this to you as I am not familiar.

**Comment by shankari** [comment]
I'm moving this to the milestone given user reports. I'll move something else out instead.

**Comment by shankari** [comment]
Should have been fixed as part of https://github.com/NREL/crowdsource-mask-wearing/pull/42/commits/8a1ae553d889d252c71e174a375f4f2430a47bbd
Will reopen if not.
