### ISSUE TITLE
Session guard for the create mask screen

### ISSUE THREAD

**Issue by shankari** [NREL/crowdsource-mask-wearing#15]
The create mask screen currently does not have a guard. Users can navigate to <URL>/create when logged in and start entering data. The data won't actually save because the `sessionid` field is required on the server, but it could be confusing. 

Maybe we want to add a guard, a `SessionGuard` similar to the `AuthGuard` to ensure that users are logged in, to ensure that a session has been started before users can enter data. If the `SessionGuard` fails, then the user should be redirected to the `/session/start` page.

**Comment by andyduvall** [comment]
Seems important. Do if possible.

**Comment by shankari** [comment]
Fixed in #40
