### ISSUE TITLE
Support ending the session before the goal is reached

### ISSUE THREAD

**Issue by shankari** [NREL/crowdsource-mask-wearing#17]
Currently, the "End session" and the session notes are only enabled when the goal is reached. It would be good to extend this to also support ending the session before the goal is reached. If the user tries to end the session before the goal is reached, we want to allow them to resume the session or to really end it.

This screenshot may help clarify.

<img width="1225" alt="Screen Shot 2020-07-27 at 2 17 48 PM" src="https://user-images.githubusercontent.com/2423263/88593155-fd3fe300-d013-11ea-8b7d-c4911745fbfb.png">

**Comment by andyduvall** [comment]
First or second priority, as this will be important for sessions in small town/rural areas, or for when a reporter doesn't have enough time to wait until 100 count quota is reached.

**Comment by shankari** [comment]
Fixed in #37 and #42
