### ISSUE TITLE
Color scheme + fit-and-finish fixes

### ISSUE THREAD

**Issue by shankari** [NREL/crowdsource-mask-wearing#18]
Create a custom color palette for the project that is consistent with NREL guidelines (blue/white).
- add green for displaying mask wearing
Change the colors/L&F to match the new color palette
Make sure that mask display (mask button/mask count) are in green

**Comment by andyduvall** [comment]
Perhaps 2nd or 3rd priority after NREL branding, if only for consistency. Not sure how heavy a lift this is.

**Comment by shankari** [comment]
Also, @nwunder said that the current menu bar used a mixture of bootstrap and angular components and was "a hot mess". Would be nice to clean that up at the same time. Not sure if angular and bootstrap play well together. 

Do we even need boostrap if we have angular?

**Comment by shankari** [comment]
More feedback from Alyssa:
- format date/time for the session display (both in the list and the map) correctly
- clearer instructions for how to collect the data for good results

**Comment by shankari** [comment]
Display the user as "You" when displaying "ALL" reports, suggested by Stan

**Comment by shankari** [comment]
@fua0004673 if you have time, can you also add a placeholder onboarding screen to be displayed after the user logs in? I think we will need to provide some more "training" on the data collection and we won't want to do it every time. We will have to tweak this based on feedback going forward, but @andyduvall and I can do that together.

**Comment by shankari** [comment]
@fua0004673 @ryanwilliamson01 

There are a couple of fit-and-finish fixes pending. I highlighted these in my review comments, but again:
- I believe that there are still bootstrap elements in the header/menubar/sidebar. I haven't seen any changes to that (https://github.com/NREL/crowdsource-mask-wearing/issues/18#issuecomment-665970883)
- Change the currently active user to display "You" (request by stan) (https://github.com/NREL/crowdsource-mask-wearing/issues/18#issuecomment-667249256)
- Placeholder onboarding screen for instructions (https://github.com/NREL/crowdsource-mask-wearing/issues/18#issuecomment-667414971). I assume this is a material dialog, but it should:
(1) support displaying multiple screens in a carousel like interface where users can go front and back
(2) popup up on first login only (store localStorage to indicate first/subsequent logins)
(3) have a ? button in the header that will bring it up again

I can help with (2) if you need it, but it is really straightforward

**Comment by shankari** [comment]
Some small formatting issues after looking at the staging site:
- I am a bit surprised at the progressbar on the tally page showing mask/no mask proportion. Progress bars typically show progress towards a goal, and we have a goal here. Would it make more sense to show reports / goal.
- Can the mask button be green as outlined in the description here? It was originally blue because it was the angular default, not because I wanted it that way

Some of the formatting seems to be a bit awkward on iPhone 6/7/8 screens - see below

| Buttons too small? [1] | Row buttons getting cut off [2] | horizontal flow looks weird [3] |
|---------|--------|--------|
| ![small_bottom_sheet](https://user-images.githubusercontent.com/2423263/89125670-e88ca080-d494-11ea-9ad1-951500385e08.png) | ![cutoff_button](https://user-images.githubusercontent.com/2423263/89125668-e62a4680-d494-11ea-87c2-a870ae06f8cc.png) | ![list_bottom_sheet](https://user-images.githubusercontent.com/2423263/89125669-e75b7380-d494-11ea-9849-5405b51b5719.png) | 

[1] I'm concerned that the bottom sheet is too small, especially on a smartphone, especially if seniors need to use it. There's no reason for the bottom sheet to be so small, is there? Why not make the sheet and the buttons bigger?
[2] Not sure why the buttons are in a row and not a column like they were.
[3] There's a ton of whitespace on the sides - it looks like it is again in a row flow and not a column. Will this be fixed by #44?

**Comment by ryanwilliamson01** [comment]
Still working through the bootstrap stuff as I find it. A onboarding workflow is a fair amount of work. I will see if I can get to it.
I fixed 2 & 3 already. Will fix 1. Sure I can make the button green. I wasn't sure how we wanted the progress bar to work - now that we have an end session early button. Happy to make that change.

**Comment by ryanwilliamson01** [comment]
For onboarding do we want to do something like this instead? https://github.com/rosen-group/ngx-onboarding

**Comment by shankari** [comment]
@ryanwilliamson01 wrt "For onboarding do we want to do something like this instead?" That's essentially a walkthrough. What we want is more of a tutorial with instructions on how to record - e.g.
- do not record children in strollers or carriers,
- if somebody has the mask below their nose, record it as no mask...

You don't have to program the entire onboarding workflow; we will tweak it going forward anyway.
Just:
- create an angular dialog that is automatically launched the first time the user signs in
- add a "help" button to the top that allows users to launch the dialog on demand

You can track first sign in using a variable in `localStorage`, similar to how the current username/password are stored. LMK if you need help with this part.

**Comment by shankari** [comment]
Created new issues for the pending tasks (#48, #49). Closing this to finish off the milestone
