### ISSUE TITLE
Play sounds when the mask/no mask buttons are pressed

### ISSUE THREAD

**Issue by shankari** [NREL/crowdsource-mask-wearing#19]
Ideally, we would cache the sounds locally instead of retrieving them every time. Or can we use ring tones instead? Need to investigate WebAPI for details.

**Comment by andyduvall** [comment]
Again, whatever is simplest, but in trying to think through the user experience, it would make sense to have an audio confirmation so that focus could be on observing people, rather than looking at the screen.

**Comment by shankari** [comment]
wrt "can we use ring tones instead"? here's a document on using the web audio API. This seems like a lighterweight approach than using a sound file, although it may be a bit more work.
https://css-tricks.com/form-validation-web-audio/

**Comment by shankari** [comment]
Fixed in #38
