### ISSUE TITLE
Allow users to submit feedback on the data collection process

### ISSUE THREAD

**Issue by shankari** [NREL/crowdsource-mask-wearing#20]
We should handle this as a separate object since it is not tied to a particular session or a report, but there can be multiple items of feedback at different times.

This should be fairly straightforward

- simple CRUD object on the server
   - create feedback
   - get list of feedback
   - delete feedback

+ feedback screen with new + list + delete on the frontend
   - new app feature using the existing feature boilerplate

**Comment by andyduvall** [comment]
If straight forward, this could be useful during the initial phase when we're getting up to speed. Alternatively, could just set up an email address to collect feedback.

**Comment by shankari** [comment]
Moving this out of the milestone given that there are additional fit and finish issues in #18 now.
