### ISSUE TITLE
Fix/improve visualization

### ISSUE THREAD

**Issue by shankari** [NREL/crowdsource-mask-wearing#21]
The location entries have now moved to the session.

Individual reports are associated with a session id, so they need to be joined to associate location with the reports. But given that all the reports in a session will be at the same place, should we even try to visualize reports spatially? Maybe it is better to visualize sessions and to use the reports to change the visualization characteristics (e.g. color/shade) instead.

In that case, should we list reports, or list sessions for a user? Maybe the list view should be a datatable of sessions and the detail of each session should be the list of reports along with some bar charts.

**Comment by andyduvall** [comment]
Probably not high priority. I vote for the simplest solution.

**Comment by shankari** [comment]
This is currently broken, so we should fix it before we go live. But I agree that the simplest working solution is fine for now.

**Comment by fua0004673** [comment]
@shankari we can discuss this in more detail moving forwards but I think the logic to join the session ID to the individual mask reports to get the location of the report makes sense to be done on the backend so that when we call `GET` on `maskreports` there is an existing field for location on the response object to obviate the need to do another call to find the location on the frontend

**Comment by shankari** [comment]
@fua0004673 as I said above, I think we should just visualize sessions instead of reports. All reports will have the same location entry. The session has the `totalCount`, `maskCount` and `nomaskCount` values already (https://github.com/NREL/crowdsource-mask-wearing/pull/12/commits/6c0370d243db3376385b0240d62b8af0d37ab196).

What additional information do you get from the actual mask reports?

Good point that I need to add an API call to retrieve sessions.

**Comment by fua0004673** [comment]
@shankari ah understood, I missed your comment to visualize just the sessions instead but that makes sense to me & should be simpler overall. 

Once an endpoint that exposes sessions is implemented I’ll go ahead and make the change on our end, thanks!

**Comment by shankari** [comment]
Fixed in #26. Will file new issue for other visualization required.
